function mytest2
    GUI = struct;
    GUI.a = 1;
    GUI.fh = figure;
    GUI.h1 = uicontrol('style','Edit',...
                       'string','0 0 1 1 0 0',...
                       'Units','normalized',...
                       'Position',[0.1 0.8 0.8 0.2],...
                       'backgroundcolor','w',...
                       'Tag','EditField');
    GUI.h2 = uicontrol('style','Edit',...
                       'string','(hkl) [uvw]',...
                       'Units','normalized',...
                       'Position',[0.1 0.1 0.8 0.2],...
                       'backgroundcolor','c',...
                       'Tag','EditField2',...
                       'Enable','off');
    GUI.h3 = uicontrol('Style','PushButton',...
                       'String','Save and display',...
                       'Units','normalized',...
                       'Position',[0.1 0.4 0.8 0.15],...
                       'callback',{@func_compute},...
                       'backgroundcolor',...
                       'r','FontSize',12);
    function func_compute(~,~)
        
        GUI.h2.String = "("+GUI.h1.String(1:5)+") "+"["+GUI.h1.String(7:11)+"]";
        assignin('base','hkluvw',GUI.h1.String);
        pause(2)
        close(GUI.fh)
    end
 end